/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.securitymodel;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SecMFStandaloneSetup extends SecMFStandaloneSetupGenerated {

	public static void doSetup() {
		new SecMFStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
