/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.securitymodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SecMFRuntimeModule extends AbstractSecMFRuntimeModule {

//	@Override
//	public Class<? extends org.eclipse.xtext.naming.IQualifiedNameProvider> bindIQualifiedNameProvider() {
//		return SMFQualifiedNameProvider.class;
//	}
//
//	public Class<? extends IQualifiedNameConverter> bindIQualifiedNameConverter() {
//		return SMFQualifiedNameConverter.class;
//	}
//
//	public Class<? extends ICrossReferenceSerializer> bindICrossReferenceSerializer() {
//		return SecMFCrossReferenceSerializer.class;
//	}
//
//	@Override
//	public Class<? extends ISerializer> bindISerializer() {
//		return SecMFSerializer.class;
//	}
//
//	@Override
//	public void configureIScopeProviderDelegate(Binder binder) {
//		binder.bind(IScopeProvider.class).annotatedWith(Names.named(AbstractDeclarativeScopeProvider.NAMED_DELEGATE))
//		.to(SMFImportedNamespaceAwareLocalScopeProvider.class);
//	}
//
//	public Class<? extends TextRegionAccessBuilder> bindTextRegionAccessBuilder() {
//		return Aadl2TextRegionAccessBuilder.class;
//	}
//
//	@Override
//	public Class<? extends IGlobalScopeProvider> bindIGlobalScopeProvider() {
//		return EClassGlobalScopeProvider.class;
//	}
}
