/*
 * generated by Xtext 2.20.0
 */
package org.sireum.aadl.osate.securitymodel.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.sireum.aadl.osate.securitymodel.ui.contentassist.antlr.AnnexAwareEntryPointFinder;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class SecMFUiModule extends AbstractSecMFUiModule {

	public SecMFUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}

	public Class<? extends org.eclipse.xtext.ui.editor.contentassist.antlr.EntryPointFinder> bindEntryPointFinder() {
		return AnnexAwareEntryPointFinder.class;
	}
}
